export const CREATE_SERVICE = "CREATE_SERVICE";
export const RETRIEVE_SERVICES = "RETRIEVE_SERVICES";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const DELETE_ALL_SERVICES = "DELETE_ALL_SERVICES";